Bump minimum Python and Ansible versions
Running ansible-galaxy inside a tenks venv was failing on Ubuntu 22.04
with the following error:

    AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

Bump minimum Python and Ansible versions and switch from os_ironic
module to openstack.cloud.baremetal_node.

This drops support for Python versions below 3.9. The branch stable/2.0
can be used where Python 3.6 or 3.8 are required.

Also drop centos8s and ubuntu-focal CI jobs which are only used in
unmaintained branches.

Change-Id: Ia740e9d8455fd9424378fa31b3495149db31c8e7